Library sketch using upvalues for fields

diff --git a/carton-build-dist b/carton-build-dist
--- a/carton-build-dist
+++ b/carton-build-dist
@@ -1,5 +1,8 @@
+#!/bin/bash
 #
-# Copyright (c) 2012-2013 Red Hat, Inc. All rights reserved.
+# Build a commit distribution tarball
+#
+# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
 #
 # This copyrighted material is made available to anyone wishing
 # to use, modify, copy, or redistribute it subject to the terms
@@ -15,24 +18,23 @@
 # Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 # Boston, MA 02110-1301, USA.
 
-dist_bin_SCRIPTS = \
-    carton-env \
-    carton-build \
-    carton-publish \
-    carton-update
+set -e -u -o pipefail -o noclobber
+CARTON_ENV=`carton-env`
+eval "$CARTON_ENV"
 
-dist_pkgdata_DATA = \
-    carton.sh
+. carton.sh
 
-CARTON_LIB_DIR = $(pkgdatadir)
-CARTON_DATA_DIR = $(localstatedir)/lib/carton
+if [ $# != 2 ]; then
+    echo "Invalid number of arguments" >&2
+    echo "Usage: `basename \"\$0\"` PROJECT_NAME COMMITTISH" >&2
+    exit 1
+fi
+declare project_name="$1"
+declare committish="$2"
 
-install-data-hook:
-	$(MKDIR_P) "$(DESTDIR)$(CARTON_DATA_DIR)"
-	mkdir "$(DESTDIR)$(CARTON_DATA_DIR)/project"
-	mkdir "$(DESTDIR)$(CARTON_DATA_DIR)/repo"
+if ! carton_name_is_valid "$project_name"; then
+    echo "Invalid project name: $project_name" >&2
+    exit 1
+fi
 
-install-exec-hook:
-	$(SED) -e 's#\(CARTON_LIB_DIR=\).*#\1"$(CARTON_LIB_DIR)"#' \
-           -e 's#\(CARTON_DATA_DIR=\).*#\1"$(CARTON_DATA_DIR)"#' \
-           -i "$(DESTDIR)$(bindir)/carton-env"
+carton_build_dist "$project_name" "$committish"
